# Generated by Django 4.1.3 on 2022-11-29 21:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_siteinfo_delete_about_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='pic',
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
