# Generated by Django 4.1.3 on 2022-12-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_post_options_alter_post_managers_and_more'),
        ('apps', '0013_alter_message_options_message_status'),
    ]

    operations = [
    ]
