# Generated by Django 4.1.3 on 2022-12-13 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_user_email_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
