# Generated by Django 4.1.3 on 2022-12-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
